import json, os

# Read template
with open('template.html', 'r') as f:
    template = f.read()

def generate_mockup(m):
    nav_items = m["nav_items"].split("|")
    nav_html = "".join([f'<li><a href="#">{item}</a></li>' for item in nav_items])
    features_html = ""
    for icon, title, desc in m["features"]:
        features_html += f'  <div class="feature-item"><div class="icon">{icon}</div><h4>{title}</h4><p>{desc}</p></div>\n'
    stats_html = ""
    for num, label in m["stats"]:
        stats_html += f'        <div><div class="number">{num}</div><div class="label">{label}</div></div>\n'
    cards_html = ""
    for title, desc in m["cards"]:
        cards_html += f'      <div class="card"><div class="card-img">{title}</div><div class="card-body"><h3>{title}</h3><p>{desc}</p></div></div>\n'
    testimonials_html = ""
    for quote, author in m["testimonials"]:
        testimonials_html += f'      <div class="testimonial"><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div><p>"{quote}"</p><div class="author">{author}</div></div>\n'
    footer_menu_html = "".join([f'<a href="#">{item}</a><br>' for item in m["footer_menu"]])
    footer_menu2_html = "".join([f'<a href="#">{item}</a><br>' for item in m["footer_menu2"]])
    footer_contact_html = "".join([f'<p>{item}</p>' for item in m["footer_contact"]])
    name_parts = m["name"].split(" ", 1)
    logo = f'{name_parts[0]} <span>{name_parts[1]}</span>' if len(name_parts) > 1 else f'<span>{m["name"]}</span>'

    body = f"""
<nav><div class="inner">
  <div class="logo serif">{logo}</div>
  <ul>{nav_html}</ul>
  <a href="#" class="cta-btn">{m["cta"]}</a>
</div></nav>

<section class="hero">
  <div class="hero-content">
    <div class="hero-badge">{m["hero_badge"]}</div>
    <h1 class="serif">{m["hero_h1"]}</h1>
    <p>{m["hero_p"]}</p>
    <div class="hero-buttons">
      <a href="#" class="btn-primary">{m["cta"]} &#8594;</a>
      <a href="#" class="btn-secondary">View Menu</a>
    </div>
  </div>
</section>

<div class="features-strip"><div class="inner">
{features_html}</div></div>

<section class="about-section">
  <div class="section-inner about-grid">
    <div class="about-image">{m["about_quote"]}</div>
    <div class="about-text">
      <h2 class="serif">{m["about_h2"]}</h2>
      <p>{m["about_p1"]}</p>
      <p>{m["about_p2"]}</p>
      <div class="highlight">
{stats_html}      </div>
    </div>
  </div>
</section>

<section>
  <div class="section-inner">
    <div class="section-header">
      <div class="overline">{m["cards_overline"]}</div>
      <h2 class="serif">{m["cards_h2"]}</h2>
      <p>{m["cards_p"]}</p>
    </div>
    <div class="cards-grid">
{cards_html}    </div>
  </div>
</section>

<section class="testimonials">
  <div class="section-inner">
    <div class="section-header">
      <div class="overline">Guest Reviews</div>
      <h2 class="serif">What People Are Saying</h2>
    </div>
    <div class="testimonial-grid">
{testimonials_html}    </div>
  </div>
</section>

<section class="cta-banner">
  <h2 class="serif">{m["cta_h2"]}</h2>
  <p>{m["cta_p"]}</p>
  <a href="#" class="btn-primary">Reserve Now &#8594;</a>
</section>

<footer><div class="inner">
  <div><div class="brand serif">{m["name"]}</div><p>{m["footer_desc"]}</p></div>
  <div><h4>Menu</h4>{footer_menu_html}</div>
  <div><h4>{m["footer_menu2_title"]}</h4>{footer_menu2_html}</div>
  <div><h4>Contact</h4>{footer_contact_html}</div>
</div><div class="bottom">Design concept by RAGA Marketing &mdash; ragamarketing.com</div></footer>"""

    html = template.replace("{{PRIMARY_COLOR}}", m["primary"])
    html = html.replace("{{PRIMARY_DARK}}", m["primary_dark"])
    html = html.replace("{{ACCENT_COLOR}}", m["accent"])
    html = html.replace("{{BG_COLOR}}", m["bg"])
    html = html.replace("{{BG_ALT}}", m["bg_alt"])
    html = html.replace("{{TEXT_COLOR}}", m["text"])
    html = html.replace("{{TEXT_LIGHT}}", m["text_light"])
    html = html.replace("{{HERO_GRADIENT_END}}", m["hero_end"])
    html = html.replace("{{BUSINESS_NAME}}", m["name"])
    html = html.replace("{{TAGLINE}}", m["tagline"])
    html = html.replace("{{BODY_CONTENT}}", body)
    return html

mockups = [
    {"slug":"st-johns-perth","name":"St Johns","tagline":"Bar & Restaurant","town":"Perth","primary":"#1a3a2a","primary_dark":"#0e2318","accent":"#c9a84c","bg":"#faf9f6","bg_alt":"#f0ede6","text":"#1a1a1a","text_light":"#5a6a5a","hero_end":"#2d5a3d","nav_items":"Home|Menu|Drinks|Events|Book","cta":"Book a Table","hero_badge":"Perth City Centre","hero_h1":"Eat, Drink &amp; <em>Celebrate</em> in Perth","hero_p":"A stylish bar and restaurant in the heart of Perth. Great food, craft cocktails and a warm welcome every time.","features":[("&#127860;","Fresh Seasonal Menu","Scottish produce daily"),("&#127867;","Craft Cocktails","Creative drinks list"),("&#127926;","Live Events","Music and entertainment"),("&#127968;","Private Dining","Events and celebrations")],"about_quote":"\"Where great food meets good times in Perth\"","about_h2":"The Heart of Perth","about_p1":"St Johns has become one of Perth's favourite spots for food, drinks and good times.","about_p2":"Our kitchen champions local Scottish produce in a relaxed, stylish setting.","stats":[("4.5","Star Rating"),("500+","Reviews"),("7","Days a Week")],"cards_overline":"Our Menu","cards_h2":"From Our Kitchen","cards_p":"Fresh Scottish dishes with a modern twist","cards":[("Lunch","Light bites and hearty mains. Perfect for a midday stop in Perth."),("Dinner","Evening menu showcasing the best Scottish produce."),("Brunch","Weekend brunch served Saturday and Sunday.")],"testimonials":[("Fantastic food and great atmosphere. One of the best in Perth.","Google Review"),("Lovely cocktails, friendly staff and incredible steak.","Google Review"),("Our go-to spot for dinner in Perth. Never disappoints.","TripAdvisor")],"cta_h2":"Your table is waiting","cta_p":"Book online for lunch, dinner or a special event.","footer_desc":"Bar &amp; Restaurant in Perth City Centre.","footer_menu":["Lunch","Dinner","Drinks","Brunch"],"footer_menu2_title":"Visit","footer_menu2":["Book Online","Private Dining","Gift Vouchers"],"footer_contact":["Perth City Centre","info@stjohnsperth.co.uk"]},
    {"slug":"taste-perthshire","name":"Taste Perthshire","tagline":"Shop & Restaurant","town":"Perth","primary":"#5a3e28","primary_dark":"#3a2818","accent":"#d4a84b","bg":"#faf8f5","bg_alt":"#f2efe9","text":"#2a2018","text_light":"#6e5e4d","hero_end":"#7a5e3a","nav_items":"Home|Menu|Shop|About|Contact","cta":"Visit Us","hero_badge":"Bankfoot, Perthshire","hero_h1":"Taste the Best of <em>Perthshire</em>","hero_p":"Award-winning shop and restaurant celebrating the finest local produce from the heart of Perthshire.","features":[("&#127860;","Farm to Table","Local Scottish produce"),("&#11088;","Award Winning","Recognised for quality"),("&#127854;","Artisan Shop","Premium local products"),("&#9749;","Coffee & Cake","Freshly baked daily")],"about_quote":"\"Celebrating the flavours of Perthshire\"","about_h2":"A Perthshire Institution","about_p1":"Taste Perthshire brings together the finest local producers under one roof.","about_p2":"From our restaurant to our shop, everything celebrates the best of Scottish food and drink.","stats":[("4.6","Star Rating"),("800+","Reviews"),("20+","Local Suppliers")],"cards_overline":"Dine & Shop","cards_h2":"What We Offer","cards_p":"Restaurant, shop and more","cards":[("Restaurant","Fresh seasonal dishes made with local Perthshire produce."),("Artisan Shop","Premium local products, gifts and hampers."),("Coffee & Cake","Freshly baked cakes and artisan coffee.")],"testimonials":[("The best farm shop and restaurant in Perthshire. A must visit.","Google Review"),("Amazing food, lovely shop, and the staff are wonderful.","Google Review"),("We stop here every time we drive through. Outstanding.","TripAdvisor")],"cta_h2":"Visit us in Bankfoot","cta_p":"Open 7 days a week for breakfast, lunch and shopping.","footer_desc":"Shop &amp; Restaurant in Bankfoot, Perthshire.","footer_menu":["Breakfast","Lunch","Shop","Hampers"],"footer_menu2_title":"Visit","footer_menu2":["Find Us","Opening Hours","Gift Vouchers"],"footer_contact":["Bankfoot, Perthshire","info@tasteperthshire.co.uk"]},
    {"slug":"angela-lamont","name":"Angela Lamont","tagline":"Hair & Beauty","town":"Perth","primary":"#8b5e83","primary_dark":"#5a3d55","accent":"#d4a0c0","bg":"#faf7f9","bg_alt":"#f2eef0","text":"#2a1a25","text_light":"#6e5a68","hero_end":"#a07898","nav_items":"Home|Services|Gallery|About|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Your Hair, Your <em>Style</em>","hero_p":"Expert hair and beauty services in the heart of Perth. Where style meets expertise.","features":[("&#128135;","Expert Stylists","Experienced team"),("&#11088;","5 Star Rated","Top reviews"),("&#128142;","Beauty Treatments","Full range"),("&#128197;","Easy Booking","Book online")],"about_quote":"\"Where confidence begins\"","about_h2":"Perth's Premier Salon","about_p1":"Angela Lamont has been helping clients look and feel their best for years.","about_p2":"From cuts and colour to beauty treatments, our expert team delivers outstanding results every time.","stats":[("5.0","Star Rating"),("200+","Reviews"),("15+","Years Experience")],"cards_overline":"Services","cards_h2":"What We Offer","cards_p":"Expert hair and beauty services","cards":[("Hair Styling","Cuts, colour, highlights and styling for every occasion."),("Beauty","Facials, waxing, tinting and skin treatments."),("Bridal","Complete bridal packages for your special day.")],"testimonials":[("Best salon in Perth. Angela and her team are amazing.","Google Review"),("Always leave feeling fabulous. Would not go anywhere else.","Google Review"),("Incredible colour work. Exactly what I wanted.","Google Review")],"cta_h2":"Book your appointment","cta_p":"Online booking available 24/7.","footer_desc":"Hair &amp; Beauty salon in Perth.","footer_menu":["Hair","Beauty","Bridal","Products"],"footer_menu2_title":"Book","footer_menu2":["Book Online","Gift Vouchers","Price List"],"footer_contact":["Perth","info@angelalamonthairandbeauty.co.uk"]},
    {"slug":"cutting-room-perth","name":"The Cutting Room","tagline":"Hair Salon","town":"Perth","primary":"#2c3e50","primary_dark":"#1a2530","accent":"#e67e22","bg":"#f9f9f9","bg_alt":"#f0f0f0","text":"#1a1a1a","text_light":"#5a5a5a","hero_end":"#3d5a78","nav_items":"Home|Services|Gallery|About|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Precision Cuts, <em>Perfect</em> Style","hero_p":"Expert hair styling for men and women in Perth city centre.","features":[("&#9986;","Expert Cuts","Precision styling"),("&#127912;","Creative Colour","Bold or natural"),("&#11088;","5 Star Service","Top rated"),("&#128197;","Easy Booking","Book online")],"about_quote":"\"Where every cut tells a story\"","about_h2":"Perth's Go-To Salon","about_p1":"The Cutting Room delivers expert hair services with a personal touch.","about_p2":"Whether you want a fresh new look or a classic style, our team has you covered.","stats":[("5.0","Star Rating"),("150+","Reviews"),("10+","Years")],"cards_overline":"Services","cards_h2":"What We Do","cards_p":"Expert hair services for everyone","cards":[("Cuts & Styling","Precision cuts for men and women."),("Colour","From natural highlights to bold transformations."),("Special Occasions","Updos and styling for events and weddings.")],"testimonials":[("Best haircut I have ever had. Stephen is brilliant.","Google Review"),("Always leave looking and feeling great. Highly recommend.","Google Review"),("Finally found my perfect salon in Perth.","Google Review")],"cta_h2":"Ready for a new look?","cta_p":"Book your appointment online today.","footer_desc":"Hair Salon in Perth City Centre.","footer_menu":["Cuts","Colour","Styling","Products"],"footer_menu2_title":"Book","footer_menu2":["Book Online","Price List","Gift Vouchers"],"footer_contact":["Perth","stephen.thecuttingroom@gmail.com"]},
    {"slug":"copperfields-perth","name":"Copperfields","tagline":"Hair & Beauty","town":"Perth","primary":"#8b4513","primary_dark":"#5a2d0a","accent":"#d4a84b","bg":"#faf8f5","bg_alt":"#f2efe9","text":"#2a1a0a","text_light":"#6e5a4a","hero_end":"#a06830","nav_items":"Home|Hair|Beauty|Gallery|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Hair &amp; Beauty <em>Excellence</em>","hero_p":"Award-winning hair and beauty salon in Perth. Where expertise meets elegance.","features":[("&#128135;","Expert Team","Highly trained stylists"),("&#128142;","Full Beauty","Comprehensive treatments"),("&#11088;","Award Winning","Recognised excellence"),("&#128197;","Book Online","24/7 booking")],"about_quote":"\"Excellence in every detail\"","about_h2":"Perth's Award-Winning Salon","about_p1":"Copperfields has been delivering exceptional hair and beauty services in Perth for years.","about_p2":"Our expert team stays at the cutting edge of trends and techniques.","stats":[("4.8","Star Rating"),("300+","Reviews"),("20+","Years")],"cards_overline":"Services","cards_h2":"Hair & Beauty","cards_p":"Complete range of services","cards":[("Hair","Cuts, colour, styling and treatments for all hair types."),("Beauty","Facials, nails, waxing and skin treatments."),("Bridal","Complete wedding packages and trial sessions.")],"testimonials":[("The best salon in Perth by far. Absolutely love it.","Google Review"),("Amazing colour work and the beauty treatments are fantastic.","Google Review"),("Would not trust my hair with anyone else. Five stars.","Google Review")],"cta_h2":"Book your visit","cta_p":"Experience the Copperfields difference.","footer_desc":"Hair &amp; Beauty in Perth.","footer_menu":["Hair","Beauty","Nails","Bridal"],"footer_menu2_title":"Visit","footer_menu2":["Book Online","Price List","Gift Vouchers"],"footer_contact":["Perth","info@copperfields.uk.com"]},
    {"slug":"rae-peacock","name":"Rae Peacock","tagline":"Hair & Beauty","town":"Perth","primary":"#4a2850","primary_dark":"#2a1830","accent":"#c9a0d4","bg":"#faf7fb","bg_alt":"#f0edf2","text":"#2a1830","text_light":"#6a5a70","hero_end":"#6a4878","nav_items":"Home|Hair|Beauty|Gallery|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Beautiful Hair, <em>Beautiful</em> You","hero_p":"Premium hair and beauty services in Perth. Expert stylists, stunning results.","features":[("&#128135;","Master Stylists","Top-trained team"),("&#128142;","Luxury Beauty","Premium treatments"),("&#11088;","5 Star Rated","Consistently excellent"),("&#127912;","Trend Leaders","Latest techniques")],"about_quote":"\"Where beauty is an art\"","about_h2":"Perth's Premium Salon","about_p1":"Rae Peacock offers a premium salon experience with exceptional results.","about_p2":"From precision cuts to luxurious beauty treatments, we deliver excellence.","stats":[("5.0","Star Rating"),("250+","Reviews"),("15+","Years")],"cards_overline":"Services","cards_h2":"Our Expertise","cards_p":"Premium hair and beauty","cards":[("Hair Styling","Expert cuts, colour and styling."),("Beauty Treatments","Facials, lashes, brows and skincare."),("Special Occasions","Wedding hair, proms and events.")],"testimonials":[("The best salon experience in Perth. Absolutely love it here.","Google Review"),("Incredible attention to detail. My hair has never looked better.","Google Review"),("Professional, friendly, and talented. Highly recommend.","Google Review")],"cta_h2":"Experience the difference","cta_p":"Book your appointment at Rae Peacock.","footer_desc":"Hair &amp; Beauty in Perth.","footer_menu":["Hair","Beauty","Bridal","Products"],"footer_menu2_title":"Book","footer_menu2":["Book Online","Gift Cards","Price List"],"footer_contact":["Perth","info@raepeacockhairandbeauty.com"]},
    {"slug":"harmony-perth","name":"Harmony","tagline":"Health & Beauty","town":"Perth","primary":"#2d6b5a","primary_dark":"#1a4a3a","accent":"#a8d4c0","bg":"#f7faf9","bg_alt":"#edf2f0","text":"#1a2a25","text_light":"#5a6e65","hero_end":"#4a8a78","nav_items":"Home|Treatments|About|Gallery|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Health, Beauty &amp; <em>Harmony</em>","hero_p":"Holistic health and beauty treatments in a peaceful Perth setting. Relax, rejuvenate, restore.","features":[("&#128142;","Beauty","Full treatment menu"),("&#129504;","Wellness","Holistic therapies"),("&#11088;","5 Star","Top rated"),("&#128197;","Easy Booking","Book online")],"about_quote":"\"Find your balance\"","about_h2":"Your Wellbeing Retreat","about_p1":"Harmony offers a haven of calm in the heart of Perth.","about_p2":"Our expert therapists deliver treatments that nurture body, mind and spirit.","stats":[("5.0","Star Rating"),("180+","Reviews"),("10+","Therapists")],"cards_overline":"Treatments","cards_h2":"Our Services","cards_p":"Beauty and wellness treatments","cards":[("Beauty","Facials, nails, waxing and skincare."),("Massage","Sports, deep tissue and relaxation massage."),("Wellness","Reflexology, aromatherapy and holistic therapies.")],"testimonials":[("The most relaxing experience. Left feeling incredible.","Google Review"),("Amazing therapists and beautiful salon. Highly recommend.","Google Review"),("My go-to for wellness in Perth. Always perfect.","Google Review")],"cta_h2":"Treat yourself","cta_p":"Book your treatment today.","footer_desc":"Health &amp; Beauty in Perth.","footer_menu":["Beauty","Massage","Wellness","Packages"],"footer_menu2_title":"Book","footer_menu2":["Book Online","Gift Vouchers","Price List"],"footer_contact":["Perth","info@harmonyhealthandbeauty.co.uk"]},
    {"slug":"park-bistro","name":"The Park Bistro","tagline":"Restaurant","town":"Linlithgow","primary":"#3a4a3a","primary_dark":"#222a22","accent":"#c9a84c","bg":"#faf9f6","bg_alt":"#f0ede6","text":"#1a1a1a","text_light":"#5a5a5a","hero_end":"#5a6a5a","nav_items":"Home|Menu|About|Gallery|Book","cta":"Book a Table","hero_badge":"Linlithgow","hero_h1":"Fine Dining in <em>Historic</em> Linlithgow","hero_p":"A neighbourhood bistro serving beautifully crafted dishes using the finest Scottish ingredients.","features":[("&#127860;","Seasonal Menu","Fresh local produce"),("&#11088;","Highly Rated","Top reviews"),("&#127863;","Fine Wines","Curated wine list"),("&#128197;","Book Online","Reserve your table")],"about_quote":"\"Where every dish tells a story\"","about_h2":"Linlithgow's Hidden Gem","about_p1":"The Park Bistro brings fine dining to the heart of historic Linlithgow.","about_p2":"Our chef creates seasonal menus that celebrate the best Scottish produce.","stats":[("4.8","Star Rating"),("350+","Reviews"),("7","Days Open")],"cards_overline":"Dining","cards_h2":"Our Menu","cards_p":"Seasonal Scottish cuisine","cards":[("Lunch","Two and three course lunch menus with daily specials."),("Dinner","Our evening tasting menu showcases the finest ingredients."),("Sunday","Traditional Sunday lunch with a modern twist.")],"testimonials":[("One of the best meals we have had in Scotland. Superb.","Google Review"),("Beautiful food, lovely setting, impeccable service.","Google Review"),("A real gem in Linlithgow. We will definitely be back.","TripAdvisor")],"cta_h2":"Your table awaits","cta_p":"Book online for an unforgettable dining experience.","footer_desc":"Restaurant in Linlithgow.","footer_menu":["Lunch","Dinner","Sunday","Wine"],"footer_menu2_title":"Visit","footer_menu2":["Book Online","Private Dining","Gift Vouchers"],"footer_contact":["Linlithgow","contact-us@theparkbistro.co.uk"]},
    {"slug":"champany-inn","name":"Champany Inn","tagline":"Restaurant & Chop House","town":"Linlithgow","primary":"#4a1a1a","primary_dark":"#2a0a0a","accent":"#d4a84b","bg":"#faf8f5","bg_alt":"#f2efe9","text":"#2a1a1a","text_light":"#6e5a5a","hero_end":"#6a2a2a","nav_items":"Home|Menu|Wine|Private|Book","cta":"Reserve Now","hero_badge":"Linlithgow","hero_h1":"Scotland's Finest <em>Steaks</em>","hero_p":"Award-winning restaurant renowned for the finest Scottish beef, exceptional seafood and an outstanding wine cellar.","features":[("&#129385;","Prime Steaks","Scottish Aberdeen Angus"),("&#127863;","Wine Cellar","Award-winning selection"),("&#11088;","Award Winning","Decades of excellence"),("&#127968;","Private Dining","Exclusive events")],"about_quote":"\"The home of Scotland's finest beef\"","about_h2":"A Scottish Institution","about_p1":"Champany Inn has been serving Scotland's finest steaks for over 40 years.","about_p2":"Our Aberdeen Angus beef is dry-aged on the premises, and our wine cellar holds over 500 bins.","stats":[("4.7","Star Rating"),("600+","Reviews"),("40+","Years")],"cards_overline":"Dining","cards_h2":"Our Offering","cards_p":"Exceptional food and wine","cards":[("Restaurant","Fine dining with Scotland's finest steaks and seafood."),("Chop House","Relaxed dining with the same quality produce."),("Wine Cellar","Over 500 bins from around the world.")],"testimonials":[("The best steak I have ever eaten. Absolute perfection.","Google Review"),("A Scottish institution. The wine list is extraordinary.","Google Review"),("Worth the drive from Edinburgh. Simply outstanding.","TripAdvisor")],"cta_h2":"An unforgettable experience","cta_p":"Reserve your table at Champany Inn.","footer_desc":"Restaurant &amp; Chop House near Linlithgow.","footer_menu":["Restaurant","Chop House","Wine","Seafood"],"footer_menu2_title":"Visit","footer_menu2":["Reserve Online","Private Dining","Gift Vouchers"],"footer_contact":["Near Linlithgow","reception@champany.com"]},
    {"slug":"nineteen62","name":"Nineteen62","tagline":"Restaurant & Bar","town":"Livingston","primary":"#1a1a2e","primary_dark":"#0a0a1e","accent":"#e6a832","bg":"#f9f9fa","bg_alt":"#f0f0f2","text":"#1a1a1a","text_light":"#5a5a6a","hero_end":"#2a2a4e","nav_items":"Home|Menu|Drinks|Events|Book","cta":"Book a Table","hero_badge":"Livingston","hero_h1":"Dine, Drink &amp; <em>Enjoy</em>","hero_p":"Modern restaurant and bar in Livingston. Great food, craft cocktails and live entertainment.","features":[("&#127860;","Modern Menu","Fresh seasonal dishes"),("&#127867;","Cocktail Bar","Craft cocktails"),("&#127926;","Live Events","Entertainment nights"),("&#128197;","Book Online","Easy reservations")],"about_quote":"\"Modern dining with a Scottish twist\"","about_h2":"Livingston's Best","about_p1":"Nineteen62 brings modern dining to Livingston with a menu that celebrates great ingredients.","about_p2":"Our bar serves craft cocktails, fine wines and local beers in a stylish setting.","stats":[("4.6","Star Rating"),("400+","Reviews"),("7","Days a Week")],"cards_overline":"Menu","cards_h2":"From Our Kitchen","cards_p":"Modern Scottish dining","cards":[("Lunch","Light bites and mains served daily."),("Dinner","Evening menu with seasonal specials."),("Weekend Brunch","Start your weekend right.")],"testimonials":[("Best restaurant in Livingston by far. Amazing food.","Google Review"),("Great cocktails and the food is always excellent.","Google Review"),("Love the atmosphere. Our favourite local spot.","Google Review")],"cta_h2":"Your table is waiting","cta_p":"Book online for any occasion.","footer_desc":"Restaurant &amp; Bar in Livingston.","footer_menu":["Lunch","Dinner","Cocktails","Brunch"],"footer_menu2_title":"Visit","footer_menu2":["Book Online","Events","Gift Vouchers"],"footer_contact":["Livingston","general@1962livingston.co.uk"]},
    {"slug":"livingston-inn","name":"Livingston Inn","tagline":"Historic Scottish Inn","town":"Livingston","primary":"#3a2818","primary_dark":"#2a1808","accent":"#c9a84c","bg":"#faf8f5","bg_alt":"#f2efe9","text":"#2a1a0a","text_light":"#6e5a4a","hero_end":"#5a4028","nav_items":"Home|Menu|History|Rooms|Book","cta":"Book a Table","hero_badge":"Livingston Village, est. 1760","hero_h1":"A Scottish Inn with <em>History</em>","hero_p":"One of Scotland's most historic inns. Great food, real ales and a warm welcome since 1760.","features":[("&#127860;","Pub Classics","Hearty Scottish food"),("&#127866;","Real Ales","Craft and cask selection"),("&#11088;","4.5 Stars","Highly rated"),("&#127968;","Historic Setting","Est. 1760")],"about_quote":"\"Hospitality since 1760\"","about_h2":"A Village Institution","about_p1":"The Livingston Inn has been welcoming guests for over 260 years.","about_p2":"Set in the charming conservation village of Livingston, we serve great food and real ales.","stats":[("4.5","Star Rating"),("300+","Reviews"),("260+","Years")],"cards_overline":"Dining","cards_h2":"From Our Kitchen","cards_p":"Hearty Scottish pub food","cards":[("Lunch","Classic pub dishes served daily."),("Dinner","Evening menu with daily specials."),("Sunday Roast","Traditional roast with all the trimmings.")],"testimonials":[("A wonderful historic pub with great food. A real gem.","Google Review"),("Best pub food in West Lothian. The beer selection is great too.","Google Review"),("Love the atmosphere of this old inn. Highly recommend.","TripAdvisor")],"cta_h2":"Pull up a seat","cta_p":"Book your table at this historic Scottish inn.","footer_desc":"Historic Inn in Livingston Village, est. 1760.","footer_menu":["Lunch","Dinner","Real Ales","Sunday Roast"],"footer_menu2_title":"Visit","footer_menu2":["Book Online","History","Gift Vouchers"],"footer_contact":["Livingston Village","info@livingstoninn.co.uk"]},
    {"slug":"hopetoun-bistro","name":"Hopetoun Bar & Bistro","tagline":"Bar & Bistro","town":"Bathgate","primary":"#2c3e50","primary_dark":"#1a2530","accent":"#e67e22","bg":"#f9f9f9","bg_alt":"#f0f0f0","text":"#1a1a1a","text_light":"#5a5a5a","hero_end":"#3d5a78","nav_items":"Home|Menu|Drinks|About|Book","cta":"Book a Table","hero_badge":"Bathgate, West Lothian","hero_h1":"Eat, Drink &amp; <em>Relax</em> in Bathgate","hero_p":"A stylish bar and bistro serving freshly prepared food and great drinks in the heart of Bathgate.","features":[("&#127860;","Fresh Food","Prepared daily"),("&#127867;","Craft Drinks","Cocktails and craft beer"),("&#11088;","Top Rated","Five star reviews"),("&#128197;","Book Online","Easy reservations")],"about_quote":"\"Bathgate's favourite bar and bistro\"","about_h2":"The Heart of Bathgate","about_p1":"Hopetoun Bar and Bistro serves freshly prepared meals in a stylish, welcoming setting.","about_p2":"From lazy brunches to evening dinners, we have something for every occasion.","stats":[("4.7","Star Rating"),("250+","Reviews"),("7","Days a Week")],"cards_overline":"Menu","cards_h2":"What We Serve","cards_p":"Fresh, locally sourced food","cards":[("Lunch","Salads, burgers, and bistro classics."),("Dinner","Evening specials and sharing plates."),("Drinks","Craft cocktails, wines and local beers.")],"testimonials":[("Best food in Bathgate. The burgers are incredible.","Google Review"),("Great atmosphere, friendly staff, delicious food.","Google Review"),("Our go-to spot. Consistently excellent.","Google Review")],"cta_h2":"Your table is waiting","cta_p":"Book online at Hopetoun Bar and Bistro.","footer_desc":"Bar &amp; Bistro in Bathgate.","footer_menu":["Lunch","Dinner","Drinks","Specials"],"footer_menu2_title":"Visit","footer_menu2":["Book Online","Events","Gift Vouchers"],"footer_contact":["Bathgate","info@hopetounbarandbistro.com"]},
    {"slug":"hilcroft-hotel","name":"Hilcroft Hotel","tagline":"Hotel & Restaurant","town":"Whitburn","primary":"#3a2a4a","primary_dark":"#2a1a3a","accent":"#c9a84c","bg":"#faf8fb","bg_alt":"#f0edf2","text":"#2a1a2a","text_light":"#6a5a6a","hero_end":"#5a4a6a","nav_items":"Home|Rooms|Restaurant|Events|Book","cta":"Book Now","hero_badge":"Whitburn, West Lothian","hero_h1":"Stay, Dine &amp; <em>Celebrate</em>","hero_p":"A welcoming hotel and restaurant in Whitburn. Perfect for overnight stays, dining and special events.","features":[("&#127968;","Comfortable Rooms","Rest and relax"),("&#127860;","Restaurant","Fresh Scottish food"),("&#127880;","Events","Weddings and functions"),("&#11088;","Highly Rated","Top reviews")],"about_quote":"\"Your home away from home\"","about_h2":"Whitburn's Finest","about_p1":"The Hilcroft Hotel offers comfortable accommodation and excellent dining.","about_p2":"Whether you are staying for business, celebrating a special occasion or just enjoying dinner, we have you covered.","stats":[("4.4","Star Rating"),("200+","Reviews"),("30+","Rooms")],"cards_overline":"Stay & Dine","cards_h2":"What We Offer","cards_p":"Accommodation, dining and events","cards":[("Rooms","Comfortable rooms for business and leisure."),("Restaurant","Scottish cuisine with seasonal menus."),("Events","Weddings, functions and private dining.")],"testimonials":[("Great hotel, lovely food and friendly staff. Will return.","Google Review"),("Perfect for our wedding reception. Could not fault it.","Google Review"),("Best hotel in the area. Clean rooms and great restaurant.","Google Review")],"cta_h2":"Book your stay","cta_p":"Rooms, dining and events at Hilcroft Hotel.","footer_desc":"Hotel &amp; Restaurant in Whitburn.","footer_menu":["Rooms","Restaurant","Bar","Events"],"footer_menu2_title":"Book","footer_menu2":["Book Room","Book Table","Weddings"],"footer_contact":["Whitburn, West Lothian","info@hilcrofthotel.com"]},
    {"slug":"emmie-hair","name":"Emmie Hair","tagline":"Hair Salon","town":"Perth","primary":"#c4788a","primary_dark":"#8a4a5a","accent":"#f0c8d0","bg":"#fdf8f9","bg_alt":"#f5eef0","text":"#2a1a20","text_light":"#6a5a60","hero_end":"#d898a8","nav_items":"Home|Services|Gallery|About|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Love Your <em>Hair</em>","hero_p":"Expert hair services in a friendly, relaxed Perth salon. Cuts, colour and styling you will love.","features":[("&#9986;","Expert Cuts","Precision styling"),("&#127912;","Creative Colour","Your perfect shade"),("&#11088;","5 Stars","Top rated"),("&#128197;","Book Online","24/7 booking")],"about_quote":"\"Hair you will love\"","about_h2":"Feel Good Hair","about_p1":"Emmie Hair delivers expert styling in a warm, welcoming salon environment.","about_p2":"Our team stays ahead of the latest trends to give you a look you love.","stats":[("5.0","Star Rating"),("100+","Reviews"),("10+","Years")],"cards_overline":"Services","cards_h2":"What We Do","cards_p":"Expert hair services","cards":[("Cuts","Precision cuts for all styles and lengths."),("Colour","From subtle highlights to bold transformations."),("Styling","Blowdries, updos and occasion styling.")],"testimonials":[("Best haircut in Perth. So happy with the result.","Google Review"),("Wonderful salon, lovely staff and great results.","Google Review"),("Finally found the perfect salon. Will not go anywhere else.","Google Review")],"cta_h2":"Ready for great hair?","cta_p":"Book your appointment today.","footer_desc":"Hair Salon in Perth.","footer_menu":["Cuts","Colour","Styling","Products"],"footer_menu2_title":"Book","footer_menu2":["Book Online","Price List","Gift Vouchers"],"footer_contact":["Perth","info@emmiehair.co.uk"]},
    {"slug":"charlie-taylor","name":"Charlie Taylor","tagline":"Salons","town":"Perth","primary":"#1a1a1a","primary_dark":"#0a0a0a","accent":"#d4a84b","bg":"#fafafa","bg_alt":"#f0f0f0","text":"#1a1a1a","text_light":"#5a5a5a","hero_end":"#333333","nav_items":"Home|Services|Team|Gallery|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Style Without <em>Limits</em>","hero_p":"Contemporary hair salon in Perth delivering cutting-edge styles with a personal touch.","features":[("&#9986;","Master Cuts","Expert precision"),("&#127912;","Bold Colour","Creative artistry"),("&#11088;","Top Rated","5 star reviews"),("&#128101;","Expert Team","Skilled stylists")],"about_quote":"\"Where style has no limits\"","about_h2":"Contemporary Styling","about_p1":"Charlie Taylor Salons brings contemporary, creative hair styling to Perth.","about_p2":"Our team of expert stylists delivers precision cuts and creative colour.","stats":[("4.9","Star Rating"),("300+","Reviews"),("20+","Years")],"cards_overline":"Services","cards_h2":"Our Expertise","cards_p":"Cutting-edge hair services","cards":[("Cut & Style","Modern cuts tailored to you."),("Colour","From classic to creative colour."),("Treatments","Keratin, Olaplex and deep conditioning.")],"testimonials":[("The best salon in Perth. Charlie and the team are incredible.","Google Review"),("Amazing creative colour work. Exactly what I wanted.","Google Review"),("Professional, talented and friendly. Top class salon.","Google Review")],"cta_h2":"Your style awaits","cta_p":"Book at Charlie Taylor Salons.","footer_desc":"Contemporary hair salon in Perth.","footer_menu":["Cuts","Colour","Treatments","Products"],"footer_menu2_title":"Book","footer_menu2":["Book Online","Meet the Team","Gift Vouchers"],"footer_contact":["Perth","charlie@charlie-taylor.co.uk"]},
    {"slug":"mcintyres-perth","name":"McIntyres","tagline":"Salons","town":"Perth","primary":"#2a2a2a","primary_dark":"#1a1a1a","accent":"#b8860b","bg":"#fafafa","bg_alt":"#f0f0f0","text":"#1a1a1a","text_light":"#5a5a5a","hero_end":"#3a3a3a","nav_items":"Home|Hair|Beauty|Team|Book","cta":"Book Now","hero_badge":"Perth","hero_h1":"Hair &amp; Beauty <em>Experts</em>","hero_p":"Perth's trusted hair and beauty destination. Expert stylists, stunning results, every time.","features":[("&#128135;","Expert Hair","Cuts, colour, styling"),("&#128142;","Full Beauty","Complete treatments"),("&#11088;","Top Rated","Excellent reviews"),("&#128101;","Skilled Team","Experienced stylists")],"about_quote":"\"Perth's trusted salon\"","about_h2":"A Perth Favourite","about_p1":"McIntyres has been a trusted name in Perth hair and beauty for years.","about_p2":"Multiple locations across the city, each delivering the same exceptional service.","stats":[("4.7","Star Rating"),("400+","Reviews"),("3","Locations")],"cards_overline":"Services","cards_h2":"Hair & Beauty","cards_p":"Complete salon services","cards":[("Hair","Cuts, colour, highlights and restyling."),("Beauty","Facials, waxing, tinting and treatments."),("Bridal","Complete wedding hair and beauty packages.")],"testimonials":[("Best salon chain in Perth. Always consistent quality.","Google Review"),("Love the Perth Road branch. My go-to salon.","Google Review"),("Great team, great results. Highly recommend McIntyres.","Google Review")],"cta_h2":"Book your appointment","cta_p":"Visit any McIntyres location in Perth.","footer_desc":"Hair &amp; Beauty Salons in Perth.","footer_menu":["Hair","Beauty","Bridal","Products"],"footer_menu2_title":"Locations","footer_menu2":["Perth Road","City Centre","Book Online"],"footer_contact":["Perth","perthroad@mcintyres.co.uk"]},
    {"slug":"dalziel-park","name":"Dalziel Park","tagline":"Hotel & Golf","town":"Motherwell","primary":"#1a3a1a","primary_dark":"#0e280e","accent":"#c9a84c","bg":"#f7faf7","bg_alt":"#edf2ed","text":"#1a2a1a","text_light":"#5a6a5a","hero_end":"#2d5a2d","nav_items":"Home|Hotel|Golf|Dining|Events","cta":"Book Now","hero_badge":"Motherwell, Lanarkshire","hero_h1":"Stay, Play &amp; <em>Dine</em>","hero_p":"A stunning hotel, golf course and restaurant set in beautiful Lanarkshire parkland.","features":[("&#127968;","Hotel","Comfortable accommodation"),("&#9971;","Golf Course","18-hole championship"),("&#127860;","Restaurant","Fine dining"),("&#127880;","Events","Weddings and functions")],"about_quote":"\"Where leisure meets luxury\"","about_h2":"Lanarkshire's Finest","about_p1":"Dalziel Park offers a complete leisure experience in beautiful parkland near Motherwell.","about_p2":"From our championship golf course to our restaurant and event spaces, we have it all.","stats":[("4.3","Star Rating"),("500+","Reviews"),("18","Holes")],"cards_overline":"Experience","cards_h2":"What We Offer","cards_p":"Hotel, golf, dining and events","cards":[("Hotel","Comfortable rooms overlooking the parkland."),("Golf","18-hole championship course with pro shop."),("Events","Weddings, conferences and private functions.")],"testimonials":[("Beautiful setting, great golf and lovely restaurant. Superb.","Google Review"),("Perfect for our wedding. The grounds are stunning.","Google Review"),("Great hotel and the golf course is in excellent condition.","Google Review")],"cta_h2":"Plan your visit","cta_p":"Book your stay, round or event at Dalziel Park.","footer_desc":"Hotel, Golf &amp; Events in Motherwell.","footer_menu":["Hotel","Golf","Restaurant","Bar"],"footer_menu2_title":"Events","footer_menu2":["Weddings","Conferences","Book Online"],"footer_contact":["Motherwell, Lanarkshire","dalziel@lisini.co.uk"]},
]

count = 0
for m in mockups:
    html = generate_mockup(m)
    filename = f'{m["slug"]}.html'
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(html)
    count += 1
    print(f"Generated {filename}")

print(f"\nTotal: {count} mockups generated")
